import { AnimatePresence, motion } from "framer-motion";
import { Headphones, X } from "lucide-react";
import { useState } from "react";

export default function AuthModal({ mode, setMode, onClose }) {
  const [submitted, setSubmitted] = useState(false);
  const signup = mode === "signup";
  return <AnimatePresence>{mode && <motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-[90] grid place-items-center bg-slate-950/80 p-4 backdrop-blur-md" onClick={onClose}><motion.div initial={{scale:.97,y:15}} animate={{scale:1,y:0}} onClick={(e)=>e.stopPropagation()} className="relative w-full max-w-md rounded-[2rem] border border-white/10 bg-slate-900 p-7 shadow-2xl sm:p-9"><button onClick={onClose} className="absolute right-4 top-4 grid h-10 w-10 place-items-center rounded-full border border-white/10 text-white"><X size={18}/></button><div className="grid h-12 w-12 place-items-center rounded-2xl bg-cyan-400 text-slate-950"><Headphones size={22}/></div>{submitted ? <div className="py-10 text-center"><h2 className="text-2xl font-black text-white">You're in!</h2><p className="mt-2 text-sm text-slate-400">Your VibeWave account UI is ready. Connect your backend to enable real authentication.</p></div> : <><p className="mt-7 text-xs font-bold uppercase tracking-[0.2em] text-cyan-400">{signup ? "Join VibeWave" : "Welcome back"}</p><h2 className="mt-2 text-3xl font-black text-white">{signup ? "Create your account" : "Sign in to continue"}</h2><p className="mt-3 text-sm leading-6 text-slate-500">{signup ? "Save favorites, track orders and unlock member offers." : "Access your saved earbuds and order history."}</p><form onSubmit={(e)=>{e.preventDefault();setSubmitted(true)}} className="mt-7 space-y-4">{signup && <input required placeholder="Full name" className="auth-input"/>}<input required type="email" placeholder="Email address" className="auth-input"/><input required type="password" placeholder="Password" className="auth-input"/><button className="w-full rounded-full bg-cyan-400 py-3.5 text-sm font-black text-slate-950">{signup ? "Create account" : "Sign in"}</button></form><button onClick={()=>setMode(signup ? "login" : "signup")} className="mt-5 w-full text-sm text-slate-500 hover:text-cyan-300">{signup ? "Already have an account? Sign in" : "New here? Create an account"}</button></>}</motion.div></motion.div>}</AnimatePresence>;
}
