import { AnimatePresence, motion } from "framer-motion";
import { Check, Heart, Minus, Plus, ShoppingBag, X } from "lucide-react";
import { useState } from "react";

export default function ProductDetails({ product, onClose, onAdd }) {
  const [qty, setQty] = useState(1);
  if (!product) return null;
  return <AnimatePresence><motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-[80] grid place-items-center bg-slate-950/80 p-4 backdrop-blur-md" onClick={onClose}>
    <motion.div initial={{scale:.96,y:18}} animate={{scale:1,y:0}} exit={{scale:.96,y:18}} onClick={(e)=>e.stopPropagation()} className="relative max-h-[92vh] w-full max-w-4xl overflow-auto rounded-[2rem] border border-white/10 bg-slate-900 shadow-2xl">
      <button onClick={onClose} className="absolute right-4 top-4 z-10 grid h-10 w-10 place-items-center rounded-full bg-slate-950/80 text-white"><X size={18}/></button>
      <div className="grid md:grid-cols-2"><div className="bg-slate-950"><img src={product.image} alt={product.name} className="h-full min-h-[340px] w-full object-cover"/></div><div className="p-7 sm:p-10"><span className="text-xs font-bold uppercase tracking-[0.2em] text-cyan-400">{product.category}</span><h2 className="mt-3 text-3xl font-black text-white sm:text-4xl">{product.name}</h2><div className="mt-4 flex items-center gap-3"><span className="text-amber-300">{"★".repeat(Math.round(product.rating))}</span><span className="text-sm text-slate-500">{product.rating} · {product.reviews} reviews</span></div><p className="mt-6 leading-7 text-slate-400">{product.description}</p><div className="mt-7 flex items-end gap-3"><span className="text-3xl font-black text-white">₹{product.price.toLocaleString("en-IN")}</span><span className="mb-1 text-sm text-slate-600 line-through">₹{product.oldPrice.toLocaleString("en-IN")}</span></div><div className="mt-7 space-y-3 text-sm text-slate-300"><p className="flex items-center gap-2"><Check size={16} className="text-cyan-400"/> Free shipping across India</p><p className="flex items-center gap-2"><Check size={16} className="text-cyan-400"/> 1-year replacement warranty</p><p className="flex items-center gap-2"><Check size={16} className="text-cyan-400"/> 7-day easy returns</p></div><div className="mt-8 flex gap-3"><div className="flex items-center rounded-full border border-white/10 bg-white/[0.03]"><button onClick={()=>setQty(Math.max(1,qty-1))} className="grid h-12 w-12 place-items-center text-white"><Minus size={16}/></button><span className="w-8 text-center text-sm font-bold text-white">{qty}</span><button onClick={()=>setQty(qty+1)} className="grid h-12 w-12 place-items-center text-white"><Plus size={16}/></button></div><button onClick={()=>onAdd(product,qty)} className="flex flex-1 items-center justify-center gap-2 rounded-full bg-cyan-400 px-5 text-sm font-black text-slate-950 transition hover:bg-cyan-300"><ShoppingBag size={18}/> Add to cart</button></div><button className="mt-3 flex w-full items-center justify-center gap-2 rounded-full border border-white/10 py-3 text-sm font-bold text-slate-300 hover:bg-white/5"><Heart size={16}/> Save to wishlist</button></div></div>
    </motion.div>
  </motion.div></AnimatePresence>;
}
